In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
indep=dataset[['age','bmi','children','sex_male','smoker_yes']]
dep=dataset['charges']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep,dep, test_size = 1/3, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf''poly','sigmoid','linear'],
           'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

In [23]:
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose=3 , n_jobs=-1 )

In [24]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
50 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
23 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'linear', 'rbf', 'poly', 'precomputed', 'sigmoid'} or a callable. Got 'rbfpoly' instead.

--------------------------------------------------------------------------------
7 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'rbf', 'precomputed', 'sigmoid', 'linear', 'poly'} or a callable. Got 'rbfpoly' instead.

--------------------------------------------------------------------------------
11 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'rbf', 'poly', 'sigmoid', 'linear', 'precomputed'} or a callable. Got 'rbfpoly' instead.

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'sigmoid', 'rbf', 'poly', 'precomputed', 'linear'} or a callable. Got 'rbfpoly' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [        nan -0.00497801  0.35511153         nan -0.00496789  0.35511153
         nan  0.47400034  0.58500764         nan  0.47370793  0.58500764
         nan  0.28290137  0.60011938         nan  0.3158464   0.60011938
         nan -0.39926793  0.59566556         nan -0.34268057  0.59566556
         nan -1.50578981  0.59513043         nan -1.56106753  0.59513043]
  warnings.warn(

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbfpoly', 'sigmoid', 'linear']},
             verbose=3)

In [29]:
re=grid.cv_results_
print("The R_score value for best parameter{}:".format(grid.best_params_),r_score)

The R_score value for best parameter{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}: 0.7567645305026379

In [30]:
table=pd.DataFrame.from_dict(re)

In [31]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002171,0.001506,0.000000,0.000000,10,auto,rbfpoly,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbfpoly'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
1,0.077782,0.014883,0.012064,0.001625,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.044787,0.081689,-0.072355,-0.027541,-0.051470,-0.004978,0.058648,16
2,0.039064,0.002147,0.006883,0.000223,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.387624,0.461268,0.288301,0.340540,0.297825,0.355112,0.063693,11
3,0.000621,0.000009,0.000000,0.000000,10,scale,rbfpoly,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbfpoly'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
4,0.050231,0.001622,0.009761,0.000397,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.043946,0.082230,-0.072132,-0.027546,-0.051337,-0.004968,0.058595,15
5,0.036819,0.002332,0.006792,0.000215,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.387624,0.461268,0.288301,0.340540,0.297825,0.355112,0.063693,11
6,0.000640,0.000041,0.000000,0.000000,100,auto,rbfpoly,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbfpoly'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
7,0.052430,0.002783,0.010342,0.000941,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.492088,0.545107,0.438714,0.468576,0.425516,0.474000,0.042447,9
8,0.043788,0.001498,0.006728,0.000062,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.596232,0.635776,0.566816,0.588799,0.537415,0.585008,0.032600,7
9,0.000638,0.000056,0.000000,0.000000,100,scale,rbfpoly,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbfpoly'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
10,0.051058,0.003397,0.009760,0.000572,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.491855,0.544604,0.439299,0.468556,0.424226,0.473708,0.042461,10
11,0.043851,0.002907,0.006682,0.000130,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.596232,0.635776,0.566816,0.588799,0.537415,0.585008,0.032600,7
12,0.000704,0.000179,0.000000,0.000000,1000,auto,rbfpoly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbfpoly'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
13,0.058043,0.004363,0.009498,0.000190,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.232428,0.306815,0.236688,0.291707,0.346868,0.282901,0.043415,14
14,0.054986,0.001933,0.007164,0.000778,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.686126,0.598398,0.586104,0.573860,0.556109,0.600119,0.045217,1
15,0.000618,0.000016,0.000000,0.000000,1000,scale,rbfpoly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbfpo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
16,0.055159,0.001405,0.009429,0.000103,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.248266,0.377692,0.315321,0.291779,0.346175,0.315846,0.044478,13
17,0.057514,0.005662,0.006643,0.000150,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.686126,0.598398,0.586104,0.573860,0.556109,0.600119,0.045217,1
18,0.000614,0.000018,0.000000,0.000000,2000,auto,rbfpoly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbfpoly'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
19,0.056361,0.003436,0.009441,0.000077,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.656854,-0.432695,-0.346330,-0.484052,-0.076409,-0.399268,0.190629,18
20,0.067984,0.003689,0.006907,0.000240,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.669958,0.592446,0.586953,0.572862,0.556109,0.595666,0.039218,3
21,0.000656,0.000044,0.000000,0.000000,2000,scale,rbfpoly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbfpo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
22,0.058428,0.003242,0.009452,0.000196,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.370980,-0.421011,-0.350248,-0.483750,-0.087414,-0.342681,0.135687,17
23,0.069344,0.005379,0.006689,0.000145,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.669958,0.592446,0.586953,0.572862,0.556109,0.595666,0.039218,3
24,0.000669,0.000047,0.000000,0.000000,3000,auto,rbfpoly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbfpoly'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
25,0.058730,0.001324,0.009320,0.000092,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.795299,-1.629662,-1.461919,-1.712710,-0.929359,-1.505790,0.308601,19
26,0.084616,0.016700,0.006723,0.000209,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.669819,0.588893,0.587076,0.572849,0.557014,0.595130,0.039068,5
27,0.000631,0.000031,0.000000,0.000000,3000,scale,rbfpoly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbfpo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
28,0.056822,0.001701,0.009331,0.000143,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.651895,-2.010670,-1.468842,-1.712109,-0.961821,-1.561068,0.346643,20
29,0.079297,0.012820,0.006213,0.001037,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.669819,0.588893,0.587076,0.572849,0.557014,0.595130,0.039068,5

In [32]:
age_input=float(input("age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("children:"))
sex_male_input=int(input("Sex Male 0 or1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

age: 32
BMI: 43
children: 2
Sex Male 0 or1: 0
Smoker Yes 0 or 1: 1

In [37]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[147500.86989059]